// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: sso/v1/sso.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on OAuthenticateCall with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *OAuthenticateCall) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OAuthenticateCall with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OAuthenticateCallMultiError, or nil if none found.
func (m *OAuthenticateCall) ValidateAll() error {
	return m.validate(true)
}

func (m *OAuthenticateCall) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return OAuthenticateCallMultiError(errors)
	}

	return nil
}

// OAuthenticateCallMultiError is an error wrapping multiple validation errors
// returned by OAuthenticateCall.ValidateAll() if the designated constraints
// aren't met.
type OAuthenticateCallMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OAuthenticateCallMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OAuthenticateCallMultiError) AllErrors() []error { return m }

// OAuthenticateCallValidationError is the validation error returned by
// OAuthenticateCall.Validate if the designated constraints aren't met.
type OAuthenticateCallValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OAuthenticateCallValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OAuthenticateCallValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OAuthenticateCallValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OAuthenticateCallValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OAuthenticateCallValidationError) ErrorName() string {
	return "OAuthenticateCallValidationError"
}

// Error satisfies the builtin error interface
func (e OAuthenticateCallValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOAuthenticateCall.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OAuthenticateCallValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OAuthenticateCallValidationError{}

// Validate checks the field values on OAuthenticateCall_Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OAuthenticateCall_Request) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OAuthenticateCall_Request with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OAuthenticateCall_RequestMultiError, or nil if none found.
func (m *OAuthenticateCall_Request) ValidateAll() error {
	return m.validate(true)
}

func (m *OAuthenticateCall_Request) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GrantType

	// no validation rules for ClientId

	// no validation rules for Username

	// no validation rules for Password

	// no validation rules for RefreshToken

	if len(errors) > 0 {
		return OAuthenticateCall_RequestMultiError(errors)
	}

	return nil
}

// OAuthenticateCall_RequestMultiError is an error wrapping multiple validation
// errors returned by OAuthenticateCall_Request.ValidateAll() if the
// designated constraints aren't met.
type OAuthenticateCall_RequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OAuthenticateCall_RequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OAuthenticateCall_RequestMultiError) AllErrors() []error { return m }

// OAuthenticateCall_RequestValidationError is the validation error returned by
// OAuthenticateCall_Request.Validate if the designated constraints aren't met.
type OAuthenticateCall_RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OAuthenticateCall_RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OAuthenticateCall_RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OAuthenticateCall_RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OAuthenticateCall_RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OAuthenticateCall_RequestValidationError) ErrorName() string {
	return "OAuthenticateCall_RequestValidationError"
}

// Error satisfies the builtin error interface
func (e OAuthenticateCall_RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOAuthenticateCall_Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OAuthenticateCall_RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OAuthenticateCall_RequestValidationError{}

// Validate checks the field values on OAuthenticateCall_Response with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OAuthenticateCall_Response) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OAuthenticateCall_Response with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OAuthenticateCall_ResponseMultiError, or nil if none found.
func (m *OAuthenticateCall_Response) ValidateAll() error {
	return m.validate(true)
}

func (m *OAuthenticateCall_Response) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AccessToken

	// no validation rules for RefreshToken

	// no validation rules for ExpiresIn

	// no validation rules for TokenType

	if len(errors) > 0 {
		return OAuthenticateCall_ResponseMultiError(errors)
	}

	return nil
}

// OAuthenticateCall_ResponseMultiError is an error wrapping multiple
// validation errors returned by OAuthenticateCall_Response.ValidateAll() if
// the designated constraints aren't met.
type OAuthenticateCall_ResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OAuthenticateCall_ResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OAuthenticateCall_ResponseMultiError) AllErrors() []error { return m }

// OAuthenticateCall_ResponseValidationError is the validation error returned
// by OAuthenticateCall_Response.Validate if the designated constraints aren't met.
type OAuthenticateCall_ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OAuthenticateCall_ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OAuthenticateCall_ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OAuthenticateCall_ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OAuthenticateCall_ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OAuthenticateCall_ResponseValidationError) ErrorName() string {
	return "OAuthenticateCall_ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e OAuthenticateCall_ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOAuthenticateCall_Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OAuthenticateCall_ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OAuthenticateCall_ResponseValidationError{}
